/**
 * Distinct professional Restaurant & Food Smart Templates.
 * Each layout has a unique composition — not color-swapped clones.
 */
import type { DesignElement, DesignElementProps } from "@/lib/design-elements";
import type { DesignData } from "@/types/db";

type SmartFieldKind =
  | "title"
  | "product"
  | "description"
  | "price"
  | "image"
  | "logo"
  | "cta"
  | "text"
  | "dynamic";

type SmartEditableField = {
  id: string;
  label: string;
  kind: SmartFieldKind;
  bindings: Array<{ elementId: string; prop: keyof DesignElementProps }>;
  defaultValue: string;
  placeholder?: string;
};

function el(
  partial: Omit<DesignElement, "rotation" | "locked" | "hidden"> &
    Partial<Pick<DesignElement, "rotation" | "locked" | "hidden">>,
): DesignElement {
  return {
    rotation: 0,
    locked: false,
    hidden: false,
    ...partial,
  };
}

function field(
  id: string,
  label: string,
  kind: SmartFieldKind,
  defaultValue: string,
  bindings: Array<{ elementId: string; prop: keyof DesignElementProps }>,
  placeholder?: string,
): SmartEditableField {
  return { id, label, kind, defaultValue, bindings, placeholder };
}

const LOGO = "/templates/good-food-logo.svg";

function apply(
  layout: string,
  theme: NonNullable<DesignData["theme"]>,
  elements: DesignElement[],
  editableFields: SmartEditableField[],
  legacy?: Partial<DesignData>,
): DesignData {
  const contentValues: Record<string, string> = {};
  for (const f of editableFields) contentValues[f.id] = f.defaultValue;

  const byId = new Map(
    elements.map((e) => [e.id, { ...e, props: { ...e.props } }]),
  );
  for (const f of editableFields) {
    const value = contentValues[f.id] ?? f.defaultValue;
    for (const b of f.bindings) {
      const target = byId.get(b.elementId);
      if (!target) continue;
      target.props = { ...target.props, [b.prop]: value };
      byId.set(b.elementId, target);
    }
  }
  const next = elements.map((e) => byId.get(e.id) ?? e);

  return {
    smart: true,
    layoutLocked: true,
    layout,
    theme,
    elements: next,
    editableFields,
    contentValues,
    ...legacy,
  };
}

function standardFields(seed: {
  restaurant: string;
  title: string;
  product: string;
  description: string;
  price: string;
  cta: string;
  image: string;
  badge: string;
  phone?: string;
  location?: string;
  hours?: string;
}): SmartEditableField[] {
  return [
    field("restaurant_name", "Restaurant Name", "title", seed.restaurant, [
      { elementId: "el_restaurant_name", prop: "text" },
    ]),
    field("logo", "Logo", "logo", LOGO, [
      { elementId: "el_logo", prop: "imageUrl" },
    ]),
    field("title", "Title", "title", seed.title, [
      { elementId: "el_title", prop: "text" },
    ]),
    field("product", "Product Name", "product", seed.product, [
      { elementId: "el_product", prop: "text" },
    ]),
    field("description", "Description", "description", seed.description, [
      { elementId: "el_description", prop: "text" },
    ]),
    field("price", "Price", "price", seed.price, [
      { elementId: "el_price", prop: "price" },
      { elementId: "el_price", prop: "text" },
    ]),
    field("image", "Product Image", "image", seed.image, [
      { elementId: "el_image", prop: "imageUrl" },
    ]),
    field("cta", "CTA", "cta", seed.cta, [
      { elementId: "el_cta", prop: "label" },
    ]),
    field("badge", "Badge", "text", seed.badge, [
      { elementId: "el_badge", prop: "text" },
    ]),
    field("phone", "Phone", "text", seed.phone ?? "+1 234 567 8900", [
      { elementId: "el_phone", prop: "text" },
    ]),
    field("location", "Location", "text", seed.location ?? "123 Food Street, NY", [
      { elementId: "el_location", prop: "text" },
    ]),
    field("hours", "Hours", "text", seed.hours ?? "Open Daily | 11AM-11PM", [
      { elementId: "el_hours", prop: "text" },
    ]),
  ];
}

/** 1) Classic menu board — two list panels, no giant hero clone. */
function layoutMenuBoard(): DesignData {
  const theme = {
    bg: "#1a1410",
    accent: "#d4a017",
    text: "#f7f1e8",
    muted: "#b8a990",
    panel: "#2a1f18",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Tonight's Menu",
    product: "Chef Selections",
    description: "Kitchen open - Fresh daily",
    price: "From $8",
    cta: "Ask your server",
    image: "/templates/heroes/menu-board.svg",
    badge: "DINNER",
    hours: "Dinner | 5PM-10PM",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_topbar",
      type: "shape",
      name: "Top bar",
      x: 0,
      y: 0,
      width: 960,
      height: 88,
      zIndex: 1,
      locked: true,
      props: { background: theme.panel },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 36,
      y: 20,
      width: 48,
      height: 48,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 100,
      y: 28,
      width: 320,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 20,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 780,
      y: 30,
      width: 140,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: 2,
        color: "#111",
        background: theme.accent,
        borderRadius: 6,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 40,
      y: 110,
      width: 500,
      height: 44,
      zIndex: 4,
      props: {
        text: seed.title,
        fontFamily: "serif",
        fontSize: 34,
        fontWeight: 700,
        color: theme.accent,
        background: "transparent",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 40,
      y: 160,
      width: 420,
      height: 36,
      zIndex: 4,
      props: {
        text: seed.description,
        fontSize: 15,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_panel_a",
      type: "shape",
      name: "Starters panel",
      x: 40,
      y: 210,
      width: 420,
      height: 220,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 16 },
    }),
    el({
      id: "el_panel_b",
      type: "shape",
      name: "Mains panel",
      x: 500,
      y: 210,
      width: 420,
      height: 220,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 16 },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Featured",
      x: 60,
      y: 230,
      width: 380,
      height: 160,
      zIndex: 4,
      props: {
        text: `${seed.product}\n\nSoup of the Day ........ $8\nHouse Salad ............. $10\nCalamari .................. $14\nGrilled Salmon ........ $28`,
        fontSize: 15,
        lineHeight: 1.45,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Accent art",
      x: 520,
      y: 230,
      width: 380,
      height: 160,
      zIndex: 3,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 12,
        background: theme.bg,
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 40,
      y: 450,
      width: 140,
      height: 48,
      zIndex: 5,
      props: {
        price: seed.price,
        fontSize: 20,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 10,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 200,
      y: 452,
      width: 180,
      height: 44,
      zIndex: 5,
      props: {
        label: seed.cta,
        fontWeight: 700,
        background: theme.panel,
        color: theme.text,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: theme.accent,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 420,
      y: 458,
      width: 160,
      height: 32,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 590,
      y: 458,
      width: 170,
      height: 32,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 770,
      y: 458,
      width: 160,
      height: 32,
      zIndex: 5,
      props: { text: seed.hours, fontSize: 12, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("menu-board", theme, elements, standardFields(seed), {
    headline: seed.title,
    price: seed.price,
  });
}

/** 2) Bold promo — huge price stamp, diagonal accent, right photo. */
function layoutFoodPromotion(): DesignData {
  const theme = {
    bg: "#0b1220",
    accent: "#ef4444",
    text: "#ffffff",
    muted: "#94a3b8",
    panel: "#1e293b",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "50% OFF",
    product: "Appetizers",
    description: "Every weekday before 6 PM - crispy bites and chef starters.",
    price: "From $6",
    cta: "Order now",
    image: "/templates/heroes/promo-red.svg",
    badge: "LIMITED TIME",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Hero",
      x: 520,
      y: 0,
      width: 440,
      height: 540,
      zIndex: 1,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_slash",
      type: "shape",
      name: "Slash",
      x: 450,
      y: -40,
      width: 120,
      height: 620,
      zIndex: 2,
      locked: true,
      rotation: 12,
      props: { background: theme.accent, opacity: 90 },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 40,
      y: 36,
      width: 44,
      height: 44,
      zIndex: 6,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 100,
      y: 44,
      width: 300,
      height: 28,
      zIndex: 6,
      props: {
        text: seed.restaurant,
        fontSize: 16,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 40,
      y: 120,
      width: 180,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: 2,
        color: "#111",
        background: theme.accent,
        borderRadius: 4,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 40,
      y: 170,
      width: 400,
      height: 90,
      zIndex: 5,
      props: {
        text: seed.title,
        fontFamily: "sans",
        fontSize: 72,
        fontWeight: 900,
        color: theme.accent,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 40,
      y: 270,
      width: 380,
      height: 40,
      zIndex: 5,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 32,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 40,
      y: 320,
      width: 380,
      height: 56,
      zIndex: 5,
      props: {
        text: seed.description,
        fontSize: 15,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 40,
      y: 400,
      width: 160,
      height: 56,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 24,
        fontWeight: 800,
        color: "#111",
        background: theme.text,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 220,
      y: 406,
      width: 180,
      height: 48,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.accent,
        color: "#fff",
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 40,
      y: 490,
      width: 200,
      height: 28,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 250,
      y: 490,
      width: 200,
      height: 28,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 470,
      y: 490,
      width: 200,
      height: 28,
      zIndex: 5,
      props: { text: "Weekdays before 6PM", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("promo-hero", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.title,
    price: seed.price,
  });
}

/** 3) Daily special — circular plate focus, story on the right. */
function layoutDailySpecial(): DesignData {
  const theme = {
    bg: "#0f172a",
    accent: "#34d399",
    text: "#f9fafb",
    muted: "#9ca3af",
    panel: "#1f2937",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Chef's Daily Special",
    product: "Pan-seared Duck Breast",
    description: "Cherry reduction, roasted vegetables, silky potato puree.",
    price: "$29",
    cta: "Order tonight",
    image: "/templates/heroes/daily-special.svg",
    badge: "TODAY ONLY",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_ring",
      type: "shape",
      name: "Plate ring",
      x: 60,
      y: 90,
      width: 360,
      height: 360,
      zIndex: 2,
      locked: true,
      props: {
        background: theme.panel,
        borderRadius: 999,
        borderWidth: 4,
        borderColor: theme.accent,
      },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Dish",
      x: 90,
      y: 120,
      width: 300,
      height: 300,
      zIndex: 3,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 999,
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 500,
      y: 40,
      width: 40,
      height: 40,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 556,
      y: 48,
      width: 340,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 16,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 500,
      y: 120,
      width: 160,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: 2,
        color: theme.accent,
        background: "transparent",
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 500,
      y: 160,
      width: 400,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.title,
        fontSize: 16,
        fontWeight: 600,
        color: theme.muted,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 500,
      y: 200,
      width: 400,
      height: 70,
      zIndex: 5,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 36,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 500,
      y: 280,
      width: 400,
      height: 70,
      zIndex: 5,
      props: {
        text: seed.description,
        fontSize: 15,
        lineHeight: 1.45,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 500,
      y: 380,
      width: 130,
      height: 52,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 26,
        fontWeight: 800,
        color: "#052e1c",
        background: theme.accent,
        borderRadius: 14,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 650,
      y: 384,
      width: 200,
      height: 48,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.panel,
        color: theme.text,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: theme.accent,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 500,
      y: 480,
      width: 140,
      height: 28,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 650,
      y: 480,
      width: 160,
      height: 28,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 820,
      y: 480,
      width: 120,
      height: 28,
      zIndex: 5,
      props: { text: "Tonight only", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("special-split", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.product,
    price: seed.price,
  });
}

/** 4) Happy hour — centered bar board with drink rows. */
function layoutHappyHour(): DesignData {
  const theme = {
    bg: "#14081f",
    accent: "#f472b6",
    text: "#fdf4ff",
    muted: "#d8b4fe",
    panel: "#2e1065",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Happy Hour",
    product: "Half-Price Cocktails",
    description: "Mon-Fri | 4:00-7:00 PM",
    price: "From $4",
    cta: "Visit the bar",
    image: "/templates/heroes/happy-hour.svg",
    badge: "BAR SPECIALS",
    hours: "Happy Hour | 4PM-7PM",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Glow art",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 1,
      locked: true,
      props: { imageUrl: seed.image, fit: "cover", opacity: 40, dataSource: "product", field: "image" },
    }),
    el({
      id: "el_board",
      type: "shape",
      name: "Board",
      x: 180,
      y: 60,
      width: 600,
      height: 400,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 24, shadow: "lg" },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 440,
      y: 80,
      width: 40,
      height: 40,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 220,
      y: 128,
      width: 520,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 14,
        fontWeight: 700,
        letterSpacing: 3,
        color: theme.muted,
        background: "transparent",
        align: "center",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 360,
      y: 165,
      width: 200,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 11,
        fontWeight: 800,
        letterSpacing: 2,
        color: "#111",
        background: theme.accent,
        borderRadius: 999,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 220,
      y: 210,
      width: 520,
      height: 40,
      zIndex: 5,
      props: {
        text: seed.title,
        fontFamily: "script",
        fontSize: 36,
        fontWeight: 600,
        color: theme.accent,
        background: "transparent",
        align: "center",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 220,
      y: 260,
      width: 520,
      height: 40,
      zIndex: 5,
      props: {
        text: seed.product,
        fontSize: 28,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        align: "center",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 260,
      y: 310,
      width: 440,
      height: 40,
      zIndex: 5,
      props: {
        text: `${seed.description}\nHouse Margarita $6  |  Old Fashioned $7  |  Draft $4`,
        fontSize: 14,
        color: theme.muted,
        background: "transparent",
        align: "center",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 320,
      y: 380,
      width: 140,
      height: 48,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 20,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 480,
      y: 382,
      width: 160,
      height: 44,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.text,
        color: theme.bg,
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 220,
      y: 500,
      width: 160,
      height: 24,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 400,
      y: 500,
      width: 180,
      height: 24,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 600,
      y: 500,
      width: 180,
      height: 24,
      zIndex: 5,
      props: { text: seed.hours, fontSize: 11, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("happy-hour", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.product,
    price: seed.price,
  });
}

/** 5) Breakfast — warm banner strip + horizontal platter. */
function layoutBreakfast(): DesignData {
  const theme = {
    bg: "#fff7ed",
    accent: "#ea580c",
    text: "#431407",
    muted: "#9a3412",
    panel: "#ffedd5",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Breakfast All Day",
    product: "Eggs Benedict Plate",
    description: "Poached eggs, hollandaise, toasted brioche - until 11:30 AM.",
    price: "From $11",
    cta: "Order breakfast",
    image: "/templates/heroes/breakfast.svg",
    badge: "MORNING",
    hours: "Breakfast | 7AM-11:30AM",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_banner",
      type: "shape",
      name: "Banner",
      x: 0,
      y: 0,
      width: 960,
      height: 120,
      zIndex: 1,
      locked: true,
      props: { background: theme.accent },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 40,
      y: 36,
      width: 48,
      height: 48,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 108,
      y: 44,
      width: 360,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 20,
        fontWeight: 800,
        color: "#fff7ed",
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 760,
      y: 44,
      width: 140,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        color: theme.accent,
        background: "#fff7ed",
        borderRadius: 999,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Platter",
      x: 40,
      y: 150,
      width: 520,
      height: 280,
      zIndex: 3,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 20,
        shadow: "md",
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 590,
      y: 160,
      width: 330,
      height: 40,
      zIndex: 4,
      props: {
        text: seed.title,
        fontSize: 18,
        fontWeight: 700,
        color: theme.muted,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 590,
      y: 210,
      width: 330,
      height: 70,
      zIndex: 4,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 30,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 590,
      y: 290,
      width: 330,
      height: 70,
      zIndex: 4,
      props: {
        text: seed.description,
        fontSize: 14,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 590,
      y: 370,
      width: 130,
      height: 48,
      zIndex: 5,
      props: {
        price: seed.price,
        fontSize: 20,
        fontWeight: 800,
        color: "#fff",
        background: theme.accent,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 740,
      y: 372,
      width: 170,
      height: 44,
      zIndex: 5,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.text,
        color: "#fff7ed",
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 40,
      y: 470,
      width: 200,
      height: 28,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 260,
      y: 470,
      width: 220,
      height: 28,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 520,
      y: 470,
      width: 220,
      height: 28,
      zIndex: 5,
      props: { text: seed.hours, fontSize: 12, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("breakfast-banner", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.title,
    price: seed.price,
  });
}

/** 6) Seasonal — full-bleed photo with bottom caption bar. */
function layoutSeasonal(): DesignData {
  const theme = {
    bg: "#1c1917",
    accent: "#f97316",
    text: "#fafaf9",
    muted: "#a8a29e",
    panel: "#292524",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Autumn Harvest Bowl",
    product: "Roasted Squash Farro",
    description: "Maple vinaigrette, toasted pepitas, goat cheese, fresh herbs.",
    price: "$16",
    cta: "Available now",
    image: "/templates/heroes/seasonal.svg",
    badge: "SEASONAL",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_image",
      type: "image",
      name: "Season art",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_scrim",
      type: "shape",
      name: "Scrim",
      x: 0,
      y: 300,
      width: 960,
      height: 240,
      zIndex: 1,
      locked: true,
      props: {
        background: "linear-gradient(180deg, transparent, #1c1917ee 45%, #1c1917)",
      },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 40,
      y: 36,
      width: 44,
      height: 44,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 100,
      y: 44,
      width: 300,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 16,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 40,
      y: 330,
      width: 140,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: 2,
        color: "#111",
        background: theme.accent,
        borderRadius: 6,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 40,
      y: 370,
      width: 500,
      height: 36,
      zIndex: 5,
      props: {
        text: seed.title,
        fontSize: 18,
        fontWeight: 600,
        color: theme.muted,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 40,
      y: 408,
      width: 520,
      height: 40,
      zIndex: 5,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 32,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 40,
      y: 456,
      width: 480,
      height: 36,
      zIndex: 5,
      props: {
        text: seed.description,
        fontSize: 14,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 700,
      y: 380,
      width: 120,
      height: 52,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 24,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 700,
      y: 450,
      width: 200,
      height: 44,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.text,
        color: theme.bg,
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 40,
      y: 505,
      width: 160,
      height: 24,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 220,
      y: 505,
      width: 180,
      height: 24,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 420,
      y: 505,
      width: 200,
      height: 24,
      zIndex: 5,
      props: { text: "Through November", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("seasonal-bleed", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.title,
    price: seed.price,
  });
}

/** 7) Lunch deal — ticket / coupon style. */
function layoutLunchDeal(): DesignData {
  const theme = {
    bg: "#022c22",
    accent: "#10b981",
    text: "#ecfdf5",
    muted: "#6ee7b7",
    panel: "#064e3b",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Soup + Sandwich",
    product: "Weekday Lunch Combo",
    description: "Includes soft drink and house chips | Weekdays 11AM-3PM",
    price: "$12.95",
    cta: "Get the deal",
    image: "/templates/heroes/lunch-deal.svg",
    badge: "LUNCH DEAL",
    hours: "Lunch | 11AM-3PM",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_ticket",
      type: "shape",
      name: "Ticket",
      x: 80,
      y: 70,
      width: 800,
      height: 360,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 8, shadow: "lg" },
    }),
    el({
      id: "el_perf",
      type: "shape",
      name: "Perforation",
      x: 620,
      y: 70,
      width: 4,
      height: 360,
      zIndex: 3,
      locked: true,
      props: { background: theme.bg, opacity: 60 },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Deal art",
      x: 650,
      y: 110,
      width: 200,
      height: 200,
      zIndex: 4,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 12,
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 110,
      y: 100,
      width: 40,
      height: 40,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 165,
      y: 108,
      width: 300,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 15,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 110,
      y: 160,
      width: 160,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: 1,
        color: "#022c22",
        background: theme.accent,
        borderRadius: 4,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 110,
      y: 210,
      width: 460,
      height: 36,
      zIndex: 5,
      props: {
        text: seed.title,
        fontSize: 18,
        fontWeight: 600,
        color: theme.muted,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 110,
      y: 250,
      width: 460,
      height: 48,
      zIndex: 5,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 34,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 110,
      y: 310,
      width: 460,
      height: 48,
      zIndex: 5,
      props: {
        text: seed.description,
        fontSize: 14,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 110,
      y: 370,
      width: 150,
      height: 48,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 24,
        fontWeight: 800,
        color: "#022c22",
        background: theme.accent,
        borderRadius: 10,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 280,
      y: 372,
      width: 170,
      height: 44,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.text,
        color: theme.bg,
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 80,
      y: 470,
      width: 200,
      height: 28,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 300,
      y: 470,
      width: 220,
      height: 28,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 12, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 540,
      y: 470,
      width: 220,
      height: 28,
      zIndex: 5,
      props: { text: seed.hours, fontSize: 12, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("deal-card", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.title,
    price: seed.price,
  });
}

/** 8) New item — corner NEW ribbon, asymmetric stack. */
function layoutNewItem(): DesignData {
  const theme = {
    bg: "#0c0a09",
    accent: "#fbbf24",
    text: "#fafaf9",
    muted: "#a8a29e",
    panel: "#1c1917",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "New on the Menu",
    product: "Truffle Mushroom Flatbread",
    description: "Fontina, wild mushrooms, fresh thyme, white truffle oil.",
    price: "$18",
    cta: "Try it tonight",
    image: "/templates/heroes/new-item.svg",
    badge: "NEW",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Dish",
      x: 420,
      y: 40,
      width: 500,
      height: 460,
      zIndex: 1,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 24,
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_ribbon",
      type: "shape",
      name: "Ribbon",
      x: 780,
      y: 40,
      width: 140,
      height: 48,
      zIndex: 6,
      locked: true,
      props: { background: theme.accent, borderRadius: 0 },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 780,
      y: 48,
      width: 140,
      height: 32,
      zIndex: 7,
      props: {
        text: seed.badge,
        fontSize: 18,
        fontWeight: 900,
        letterSpacing: 3,
        color: "#111",
        background: "transparent",
        align: "center",
      },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 40,
      y: 40,
      width: 44,
      height: 44,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 100,
      y: 50,
      width: 280,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 15,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 40,
      y: 160,
      width: 340,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.title,
        fontSize: 16,
        fontWeight: 700,
        color: theme.accent,
        background: "transparent",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 40,
      y: 210,
      width: 360,
      height: 90,
      zIndex: 5,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 36,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 40,
      y: 320,
      width: 340,
      height: 70,
      zIndex: 5,
      props: {
        text: seed.description,
        fontSize: 15,
        color: theme.muted,
        background: "transparent",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 40,
      y: 410,
      width: 120,
      height: 52,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 26,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 180,
      y: 414,
      width: 180,
      height: 48,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.panel,
        color: theme.text,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: theme.accent,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 40,
      y: 500,
      width: 160,
      height: 24,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 220,
      y: 500,
      width: 180,
      height: 24,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 420,
      y: 500,
      width: 160,
      height: 24,
      zIndex: 5,
      props: { text: "Available now", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("new-item", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.product,
    price: seed.price,
  });
}

/** 9) Combo — three product slots across. */
function layoutCombo(): DesignData {
  const theme = {
    bg: "#0f0a2e",
    accent: "#818cf8",
    text: "#eef2ff",
    muted: "#a5b4fc",
    panel: "#1e1b4b",
  };
  const seed = {
    restaurant: "THE GOOD FOOD",
    title: "Feed the Table",
    product: "Family Sharing Combo",
    description: "2 pizzas + Large salad + Soft drinks | Serves 3-4",
    price: "$39.99",
    cta: "Order combo",
    image: "/templates/heroes/combo.svg",
    badge: "FAMILY COMBO",
  };
  const elements: DesignElement[] = [
    el({
      id: "el_bg",
      type: "shape",
      name: "Background",
      x: 0,
      y: 0,
      width: 960,
      height: 540,
      zIndex: 0,
      locked: true,
      props: { background: theme.bg },
    }),
    el({
      id: "el_logo",
      type: "logo",
      name: "Logo",
      x: 40,
      y: 28,
      width: 40,
      height: 40,
      zIndex: 5,
      props: { imageUrl: LOGO, fit: "contain", background: "transparent" },
    }),
    el({
      id: "el_restaurant_name",
      type: "text",
      name: "Restaurant",
      x: 96,
      y: 36,
      width: 300,
      height: 28,
      zIndex: 5,
      props: {
        text: seed.restaurant,
        fontSize: 16,
        fontWeight: 800,
        color: theme.text,
        background: "transparent",
        dataSource: "restaurant",
        field: "name",
      },
    }),
    el({
      id: "el_badge",
      type: "text",
      name: "Badge",
      x: 740,
      y: 32,
      width: 180,
      height: 32,
      zIndex: 5,
      props: {
        text: seed.badge,
        fontSize: 12,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 999,
        align: "center",
        padding: 6,
      },
    }),
    el({
      id: "el_title",
      type: "text",
      name: "Title",
      x: 40,
      y: 90,
      width: 880,
      height: 40,
      zIndex: 4,
      props: {
        text: seed.title,
        fontSize: 18,
        fontWeight: 600,
        color: theme.muted,
        background: "transparent",
        align: "center",
      },
    }),
    el({
      id: "el_product",
      type: "text",
      name: "Product",
      x: 40,
      y: 130,
      width: 880,
      height: 44,
      zIndex: 4,
      props: {
        text: seed.product,
        fontFamily: "serif",
        fontSize: 34,
        fontWeight: 700,
        color: theme.text,
        background: "transparent",
        align: "center",
        dataSource: "product",
        field: "name",
      },
    }),
    el({
      id: "el_slot_a",
      type: "shape",
      name: "Slot A",
      x: 60,
      y: 200,
      width: 260,
      height: 180,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 16 },
    }),
    el({
      id: "el_slot_b",
      type: "shape",
      name: "Slot B",
      x: 350,
      y: 200,
      width: 260,
      height: 180,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 16 },
    }),
    el({
      id: "el_slot_c",
      type: "shape",
      name: "Slot C",
      x: 640,
      y: 200,
      width: 260,
      height: 180,
      zIndex: 2,
      locked: true,
      props: { background: theme.panel, borderRadius: 16 },
    }),
    el({
      id: "el_image",
      type: "image",
      name: "Combo art",
      x: 350,
      y: 210,
      width: 260,
      height: 160,
      zIndex: 3,
      props: {
        imageUrl: seed.image,
        fit: "cover",
        borderRadius: 12,
        dataSource: "product",
        field: "image",
      },
    }),
    el({
      id: "el_description",
      type: "text",
      name: "Description",
      x: 80,
      y: 250,
      width: 220,
      height: 100,
      zIndex: 4,
      props: {
        text: "2 Pizzas\n\nLarge Salad\n\nSoft Drinks",
        fontSize: 16,
        fontWeight: 600,
        color: theme.text,
        background: "transparent",
        align: "center",
        dataSource: "product",
        field: "description",
      },
    }),
    el({
      id: "el_extra",
      type: "text",
      name: "Serves",
      x: 660,
      y: 260,
      width: 220,
      height: 80,
      zIndex: 4,
      locked: true,
      props: {
        text: "Serves\n3-4 guests",
        fontSize: 20,
        fontWeight: 700,
        color: theme.accent,
        background: "transparent",
        align: "center",
      },
    }),
    el({
      id: "el_price",
      type: "price-badge",
      name: "Price",
      x: 320,
      y: 420,
      width: 160,
      height: 52,
      zIndex: 6,
      props: {
        price: seed.price,
        fontSize: 26,
        fontWeight: 800,
        color: "#111",
        background: theme.accent,
        borderRadius: 12,
        dataSource: "product",
        field: "price",
      },
    }),
    el({
      id: "el_cta",
      type: "button",
      name: "CTA",
      x: 500,
      y: 424,
      width: 180,
      height: 48,
      zIndex: 6,
      props: {
        label: seed.cta,
        fontWeight: 800,
        background: theme.text,
        color: theme.bg,
        borderRadius: 999,
      },
    }),
    el({
      id: "el_phone",
      type: "contact",
      name: "Phone",
      x: 40,
      y: 500,
      width: 180,
      height: 24,
      zIndex: 5,
      props: { text: "+1 234 567 8900", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_location",
      type: "location",
      name: "Location",
      x: 240,
      y: 500,
      width: 200,
      height: 24,
      zIndex: 5,
      props: { text: "123 Food Street, NY", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
    el({
      id: "el_hours",
      type: "hours",
      name: "Hours",
      x: 460,
      y: 500,
      width: 200,
      height: 24,
      zIndex: 5,
      props: { text: "Available all day", fontSize: 11, color: theme.muted, background: "transparent" },
    }),
  ];
  return apply("combo", theme, elements, standardFields(seed), {
    badge: seed.badge,
    headline: seed.product,
    price: seed.price,
  });
}

export function buildDistinctRestaurantTemplates(): Record<string, DesignData> {
  return {
    "Restaurant Menu": layoutMenuBoard(),
    "Food Promotion": layoutFoodPromotion(),
    "Daily Special": layoutDailySpecial(),
    "Happy Hour": layoutHappyHour(),
    "Breakfast Menu": layoutBreakfast(),
    "Seasonal Offer": layoutSeasonal(),
    "Lunch Deal": layoutLunchDeal(),
    "New Item": layoutNewItem(),
    "Combo Promotion": layoutCombo(),
  };
}
